type = "web_pixel_extension"
name = "aiupsello-pixel"

runtime_context = "strict"

[settings]
type = "object"

[settings.fields.shop]
name = "Shop"
description = "Shop"
type = "single_line_text_field"
validations =  [
  { name = "min", value = "1" }
]

[settings.fields.host]
name = "Host"
description = "Host"
type = "single_line_text_field"
validations =  [
  { name = "min", value = "1" }
]
